MvcMyBlog/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcMyBlog.Models;

namespace MvcMyBlog.Controllers
{ 
    public class CommentController : Controller
    {
        private PostContext db = new PostContext();

        //
        // GET: /Comment/

        public ViewResult Index()
        {
            return View(db.Comments.ToList());
        }

        //
        // GET: /Comment/Details/5

        public ViewResult Details(int id)
        {
            Comment comment = db.Comments.Find(id);
            return View(comment);
        }

        //
        // GET: /Comment/Create

        
        public ActionResult Create(int PostID)
        {
            var newComment = new Comment();
            newComment.PostID = PostID;
            newComment.CommentDate = DateTime.Now;
            return View(newComment);
        } 



        //
        // POST: /Comment/Create

        [HttpPost]
        public ActionResult Create(Comment comment)
        {
            if (ModelState.IsValid)
            {
                db.Comments.Add(comment);
                db.SaveChanges();
                //return RedirectToAction("Index");  
                return View();
            }

            return View(comment);
        }
        
        //
        // GET: /Comment/Edit/5
 
        public ActionResult Edit(int id)
        {
            Comment comment = db.Comments.Find(id);
            return View(comment);
        }

        //
        // POST: /Comment/Edit/5

        [HttpPost]
        public ActionResult Edit(Comment comment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(comment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(comment);
        }

        //
        // GET: /Comment/Delete/5
 
        public ActionResult Delete(int id)
        {
            Comment comment = db.Comments.Find(id);
            return View(comment);
        }

        //
        // POST: /Comment/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            Comment comment = db.Comments.Find(id);
            db.Comments.Remove(comment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MvcMyBlog/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcMyBlog.Models;

using Microsoft.Web.Helpers;

using System.Web.Helpers;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;
using System.IO;

namespace MvcMyBlog.Controllers
{ 
    public class HomeController : Controller
    {
        private PostContext db = new PostContext();

        //
        // GET: /Post/

        public ViewResult Index()
        {
            var posts = db.Posts.Include(p => p.CategoryPost);
            return View(posts.ToList());
        }


        public ViewResult Categories(string catname)
        {
            var posts = from p in db.Posts
                         select p;

            if (!String.IsNullOrEmpty(catname))
            {
                posts = posts.Where(s => s.CategoryPost.Category==catname);
            }

            return View(posts.ToList());
        }


        public ViewResult CurrentUser(string username)
        {
            var posts = from p in db.Posts
                        select p;

            if (!String.IsNullOrEmpty(username))
            {
                posts = posts.Where(s => s.UserName == HttpContext.User.Identity.Name);
            }

            return View(posts.ToList());
        }



        //
        // GET: /Post/Details/5

        public ViewResult Details(int id)
        {
            Post post = db.Posts.Find(id);
            return View(post);
        }

        //
        // GET: /Post/Create

        
       
        public ActionResult Create()
        {
            ViewBag.CategoryPostID = new SelectList(db.CategoryPosts, "CategoryPostID", "Category");
            ViewBag.UserName = User.Identity.Name.ToString();
            ViewBag.Date = DateTime.Now;
            return View();
        } 

        //
        // POST: /Post/Create

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(Post post)
        {
            if (ModelState.IsValid)
            {
                db.Posts.Add(post);
                db.SaveChanges();
                return RedirectToAction("Index");  
            }

            ViewBag.CategoryPostID = new SelectList(db.CategoryPosts, "CategoryPostID", "Category", post.CategoryPostID);
            ViewBag.UserName = User.Identity.Name.ToString();
            return View(post);
        }
        
        //
        // GET: /Post/Edit/5
 
        public ActionResult Edit(int id)
        {
            Post post = db.Posts.Find(id);
            ViewBag.CategoryPostID = new SelectList(db.CategoryPosts, "CategoryPostID", "Category", post.CategoryPostID);
            return View(post);
        }

        //
        // POST: /Post/Edit/5

        [HttpPost]
        public ActionResult Edit(Post post)
        {
            if (ModelState.IsValid)
            {
                db.Entry(post).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryPostID = new SelectList(db.CategoryPosts, "CategoryPostID", "Category", post.CategoryPostID);
            return View(post);
        }

        //
        // GET: /Post/Delete/5
 
        public ActionResult Delete(int id)
        {
            Post post = db.Posts.Find(id);
            return View(post);
        }

        //
        // POST: /Post/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            Post post = db.Posts.Find(id);
            db.Posts.Remove(post);
            db.SaveChanges();
            return RedirectToAction("Index");
        }




        public ActionResult Upload()
        {
            var image = WebImage.GetImageFromRequest();

            if (image != null)
            {
                /*if (image.Width > 500)
                {
                    image.Resize(500, ((500 * image.Height) / image.Width));
                }*/

                var filename = Path.GetFileName(image.FileName);
                image.Save(Path.Combine("../Content/_images", filename));
                filename = Path.Combine("~/Content/_images", filename);

                //model.ImageUrl = Url.Content(filename);

            }

            return View("Index");
        }


        public ActionResult SearchIndex(string title)
        {
            var posts = from p in db.Posts
                         select p;

            if (!String.IsNullOrEmpty(title))
            {
                posts = posts.Where(s => s.Title.Contains(title));
            }

            return View(posts);

        }


        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MvcMyBlog/Views/Home/About.cshtml
@{
    ViewBag.Title = "About Us";
}

<h2>About</h2>
<p>
     Put content here.
</p>

MvcMyBlog/Views/Home/Categories.cshtml
@model IEnumerable<MvcMyBlog.Models.Post>

@{
    ViewBag.Title = "Categories - " + @Request["catname"];
}

 
<h2>Category - @Request["catname"]</h2>
 
     

@foreach (var item in Model)
{
    <article class="post col-8-wrap format-audio clearfix">
						
						<!--
                        
                        <figure class="col-3">
							<a href="blog_single.html"><img src="_images/assets/entry-3-col-2-list.jpg" width="220" height="157" alt="Threaded Awesomeness"></a>
						</figure>

                        -->

						<header>
							<h3 class="post-title" style="padding-left:9px;">@Html.ActionLink(item.Title.ToString(), "Details", new { id=item.PostID })</h3>
						</header>
						<div class="entry">
							<p>@Html.DisplayTextFor(modelItem => item.Text)</p>                 
						</div>
						<div class="cl"></div>
						<footer class="meta">
							<p><strong>Category: </strong>@Html.DisplayFor(modelItem => item.CategoryPost.Category) &nbsp;|&nbsp; <strong>Date: </strong>@Html.DisplayFor(modelItem => item.Date)    |   <a class="comments" href="">@Html.DisplayFor(modelItem => item.Comments.Count)</a>  |  <strong>Tags</strong> : @Html.DisplayFor(modelItem => item.Tags)</p>
						</footer>
					</article>
			
					<div class="cl"></div>
}


</div>    <!--  ZA DA SE ZATVORI RenderBody()    -->




<!-- Side Bar -->
					
                    <aside class="col-4">
						
						<div class="widget widget-style-1">
							<h4>Categories</h4>
							<ul>
                            @using (Html.BeginForm("Categories", "Home", FormMethod.Get)) 
                            
                            {
                                
                                <li><a href="Categories?catname=Web Design">Web Design</a></li>
                                <li><a href="Categories?catname=Graphic Design">Graphic Design</a></li>  
                                <li><a href="Categories?catname=Motion Graphics">Motion Graphics</a></li> 
                                <li><a href="Categories?catname=Usability"></a>Usability</li>
                                <li><a href="Categories?catname=Mobile apps"></a>Mobile apps</li>                                   
                                
                            }
							</ul>
						</div>
					
						<div class="widget widget-style-2">
							<h4>Archives</h4>
							<ul>
								<li><a href="#">October 2011</a></li>
								<li><a href="#">September 2011</a></li>
								<li><a href="#">August 2011</a></li>
								<li><a href="#">July 2011</a></li>
								<li><a href="#">June 2011</a></li>
							</ul>
						</div>
						
						
					</aside>

                   

				<!-- / Side Bar -->

MvcMyBlog/Views/Home/Create.cshtml
@model MvcMyBlog.Models.Post
@using Microsoft.Web.Helpers;

@{
    ViewBag.Title = "Create";
}

<h2>Create New Post</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>



@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend></legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Text)
        </div>

        <div class="editor-field">
         @Html.TextAreaFor(model => model.Text, new { @class = "ckeditor" })
         @Html.ValidationMessageFor(model => model.Text)
       </div>

      <script type="text/javascript">
      $(document).ready(function () {
        $(this).parents('form:first').submit(function () {
            for (instance in CKEDITOR.instances) {
                CKEDITOR.instances[instance].updateElement();
            }
        });
      });
      </script>

        <br />

        <div class="editor-label">
            @Html.LabelFor(model => model.ImageUrl)
        </div>

        <br />
        @using (Html.BeginForm("Upload", "Home", FormMethod.Post, new { @encType = "multipart/form-data" })) {           
        @FileUpload.GetHtml(initialNumberOfFiles: 1, allowMoreFilesToBeAdded: false, includeFormTag: false, addText: "Add Files", uploadText: "Upload File") <br />        

     
        
        }



        <div class="editor-label">
            @Html.LabelFor(model => model.CategoryPostID, "Choose Category")
        </div>
        <div class="editor-field">
            @Html.DropDownList("CategoryPostID", "-- Choose --")
            @Html.ValidationMessageFor(model => model.CategoryPostID)
          
        </div>

        <div class="editor-label">
            <!--@Html.LabelFor(model => model.Date)-->
        </div>
        <div class="editor-field" style="display:none;">
        @Html.TextBox("Date")
            <!--@Html.EditorFor(model => model.Date)-->
            @Html.ValidationMessageFor(model => model.Date)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Tags)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Tags)
            @Html.ValidationMessageFor(model => model.Tags)
        </div>

        <div class="editor-label">
           <!-- @Html.LabelFor(model => model.UserName)-->
        </div>

        <br />

        <div class="editor-field" style="display:none;">
            @Html.TextBox("UserName")
            @Html.ValidationMessageFor(model => model.UserName)
        </div>


        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}


<br />
<div>
    @Html.ActionLink("Back to Home", "Index")
</div>






</div>    <!--  ZA DA SE ZATVORI RenderBody()    -->




<!-- Side Bar -->
					
                    <aside class="col-4">
						
						<div class="widget widget-style-1">
							<h4>Categories</h4>
							<ul>
                           
                                
                                <li><a href="Categories?catname=Web Design">Web Design</a></li>
                                <li><a href="Categories?catname=Graphic Design">Graphic Design</a></li>  
                                <li><a href="Categories?catname=Motion Graphics">Motion Graphics</a></li> 
                                <li><a href="Categories?catname=Usability"></a>Usability</li>
                                <li><a href="Categories?catname=Mobile apps"></a>Mobile apps</li>                                   
                                
                            
							</ul>
						</div>
					
						<div class="widget widget-style-2">
							<h4>Archives</h4>
							<ul>
								<li><a href="#">October 2011</a></li>
								<li><a href="#">September 2011</a></li>
								<li><a href="#">August 2011</a></li>
								<li><a href="#">July 2011</a></li>
								<li><a href="#">June 2011</a></li>
							</ul>
						</div>
						
						
						
					</aside>

                   

				<!-- / Side Bar -->

MvcMyBlog/Views/Home/CurrentUser.cshtml
@model IEnumerable<MvcMyBlog.Models.Post>

@{
    ViewBag.Title = "My posts";
}

<h2>My posts</h2>

@foreach (var item in Model)
{
    <article class="post col-8-wrap format-audio clearfix">
						
						<!--
                        
                        <figure class="col-3">
							<a href="blog_single.html"><img src="_images/assets/entry-3-col-2-list.jpg" width="220" height="157" alt="Threaded Awesomeness"></a>
						</figure>

                        -->

						<header>
							<h3 class="post-title" style="padding-left:9px;">@Html.ActionLink(item.Title.ToString(), "Details", new { id=item.PostID })</h3>
						</header>
						<div class="entry">
							<p>@Html.DisplayTextFor(modelItem => item.Text)</p>                 
						</div>
						<div class="cl"></div>
						<footer class="meta">
							<p><strong>Category: </strong>@Html.DisplayFor(modelItem => item.CategoryPost.Category) &nbsp;|&nbsp; <strong>Date: </strong>@Html.DisplayFor(modelItem => item.Date)    |   <a class="comments" href="">@Html.DisplayFor(modelItem => item.Comments.Count)</a>  |  <strong>Tags</strong> : @Html.DisplayFor(modelItem => item.Tags)</p>
						</footer>
					</article>
			
					<div class="cl"></div>
}


</div>    <!--  ZA DA SE ZATVORI RenderBody()    -->




<!-- Side Bar -->
					
                    <aside class="col-4">
						
						<div class="widget widget-style-1">
							<h4>Categories</h4>
							<ul>
                            @using (Html.BeginForm("Categories", "Home", FormMethod.Get)) 
                            
                            {
                                
                                <li><a href="Categories?catname=Web Design">Web Design</a></li>
                                <li><a href="Categories?catname=Graphic Design">Graphic Design</a></li>  
                                <li><a href="Categories?catname=Motion Graphics">Motion Graphics</a></li> 
                                <li><a href="Categories?catname=Usability"></a>Usability</li>
                                <li><a href="Categories?catname=Mobile apps"></a>Mobile apps</li>                                   
                                
                            }
							</ul>
						</div>
					
						<div class="widget widget-style-2">
							<h4>Archives</h4>
							<ul>
								<li><a href="#">October 2011</a></li>
								<li><a href="#">September 2011</a></li>
								<li><a href="#">August 2011</a></li>
								<li><a href="#">July 2011</a></li>
								<li><a href="#">June 2011</a></li>
							</ul>
						</div>
						
						
					</aside>

                   

				<!-- / Side Bar -->

MvcMyBlog/Views/Home/Delete.cshtml
@model MvcMyBlog.Models.Post

@{
    ViewBag.Title = "Delete";
}

<!--<h2>Delete</h2>-->

<h3>Are you sure you want to delete this?</h3>


<!--
<fieldset>
    <legend>Post</legend>

    <div class="display-label">Title</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">Text</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Text)
    </div>

    <div class="display-label">CategoryPost</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CategoryPost.Category)
    </div>

    <div class="display-label">Date</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Date)
    </div>

    <div class="display-label">Tags</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Tags)
    </div>

    <div class="display-label">UserName</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserName)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}
-->



<article class="clearfix post format-image">
					
						
						<header class="col-8" style="position:reltive; top:11px;">
							<h3>@Html.DisplayFor(model => model.Title)</h3>
						</header>
						
						<div class="cl"></div>
						
                        <!--

						<div class="col-8 slider-wrapper">
							<div class="ribbon"></div>
							<div id="slider" class="nivoSlider">
								<img src="_images/assets/entry-8-col-1.jpg" width="620" height="300" alt="Slide 1" title="This is a caption">
								<img src="_images/assets/entry-8-col-2.jpg" width="620" height="300" alt="Slide 2">
								<img src="_images/assets/entry-8-col-3.jpg" width="620" height="300" alt="Slide 3">
							</div>
						</div>
						
						<div class="cl"></div>

                        -->
						
						<section class="col-8">
							<p>@Html.DisplayTextFor(model => model.Text)</p>
						</section>
						
						<div class="cl"></div>
							
						<footer class="meta col-8">
							<p><strong>Category: </strong>@Html.DisplayFor(model => model.CategoryPost.Category) &nbsp;|&nbsp; <strong>Date: </strong>@Html.DisplayFor(model => model.Date)    |   <a class="comments" href="">24</a>  |  <strong>Tags</strong> : @Html.DisplayFor(model => model.Tags)</p>
						</footer>
						
						<hr class="col-8" />
						
						<section class="col-2">
							<figure>
								<img src="@Url.Content("~/Content/images/post-author.jpg")" height="100" width="100" alt="Author photo">
							</figure>
						</section>
						<section class="col-6" style="position:relative; top:7px; left:-40px;">
							<h6>Author: @Html.DisplayFor(model => model.UserName)</h6>
							<p><small>
								Author Biography...
							</small></p>

                            
                           @using (Html.BeginForm())
                           {
                           <p>
                             <input type="submit" value="Delete" /> |
                             @Html.ActionLink("Back to Home", "Index")
                           </p>
                           }
							
						</section>
						
					</article>

MvcMyBlog/Views/Home/Details.cshtml
@model MvcMyBlog.Models.Post

@{
    ViewBag.Title = "Details";
}

<!--

<h2>Details</h2>

<fieldset>
    <legend>Post</legend>

    <div class="display-label">Title</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">Text</div>
    <div class="display-field">
        @Html.DisplayTextFor(model => model.Text)
    </div>


    <div class="display-label">CategoryPost</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CategoryPost.Category)
    </div>

    <div class="display-label">Date</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Date)
    </div>

    <div class="display-label">Tags</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Tags)
    </div>

    <div class="display-label">UserName</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserName)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.PostID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

-->





<article class="clearfix post format-image">
					
						
						<header class="col-8" style="position:reltive; top:11px;">
							<h3>@Html.DisplayFor(model => model.Title)</h3>
						</header>
						
						<div class="cl"></div>
						
                        <!--

						<div class="col-8 slider-wrapper">
							<div class="ribbon"></div>
							<div id="slider" class="nivoSlider">
								<img src="_images/assets/entry-8-col-1.jpg" width="620" height="300" alt="Slide 1" title="This is a caption">
								<img src="_images/assets/entry-8-col-2.jpg" width="620" height="300" alt="Slide 2">
								<img src="_images/assets/entry-8-col-3.jpg" width="620" height="300" alt="Slide 3">
							</div>
						</div>
						
						<div class="cl"></div>

                        -->
						
						<section class="col-8">
							<p>@Html.DisplayTextFor(model => model.Text)</p>
						</section>

<div style="position:relative; left:10px;">
                        <!-- Lockerz Share BEGIN -->
<div class="a2a_kit a2a_default_style">
<a class="a2a_dd" href="http://www.addtoany.com/share_save">Share</a>
<span class="a2a_divider"></span>
<a class="a2a_button_facebook"></a>
<a class="a2a_button_twitter"></a>
<a class="a2a_button_email"></a>
<a class="a2a_button_google_plus"></a>
</div>
<script type="text/javascript" src="http://static.addtoany.com/menu/page.js"></script>
<!-- Lockerz Share END -->

</div>



						
						<div class="cl"></div>
							
						<footer class="meta col-8">
							<p><strong>Category: </strong>@Html.DisplayFor(model => model.CategoryPost.Category) &nbsp;|&nbsp; <strong>Date: </strong>@Html.DisplayFor(model => model.Date)    |   <a class="comments" href="#comment">@Html.DisplayFor(model => model.Comments.Count)</a>  |  <strong>Tags</strong> : @Html.DisplayFor(model => model.Tags)</p>
						</footer>
						
						<hr class="col-8" />
						
						<section class="col-2">
							<figure>
								<img src="@Url.Content("~/Content/images/post-author.jpg")" height="100" width="100" alt="Author photo">
							</figure>
						</section>
						<section class="col-6" style="position:relative; top:7px; left:-40px;">
							<h6>Author: @Html.DisplayFor(model => model.UserName)</h6>
							<p><small>
								Author Biography...
							</small></p>


                            @if (HttpContext.Current.User.Identity.Name.ToString()==Model.UserName.ToString())
                            {
                            <p>
                            @Html.ActionLink("Edit", "Edit", new { id = Model.PostID }) | 
                            @Html.ActionLink("Delete", "Delete", new { id=Model.PostID })
                                         
                            </p>
                            }
                            
                           <p> @Html.ActionLink("Back to Home", "Index")  </p>
							
						</section>
						
					</article>








<!-- Comments -->
			
					<div id="comments" class="col-8-wrap comments">
						
						<header>
							<h3>Comments</h3>
						</header>
						
						<div class="cl"></div>
						
						<!-- Comments -->

                       
						<section class="cols-8-wrap">

						<ol class="commentlist clearfix">

                        @foreach (var item in Model.Comments)
                        {
								<li class="comment even thread-even depth-1 parent">
									<div class="comment-body">
										<div class="comment-author vcard">
											<cite class="fn">@Html.DisplayFor(modelItem => item.UserFullName)</cite>
											<span class="says">says:</span>
										</div>
										<div class="comment-meta commentmetadata">
											<a href="#comment">@Html.DisplayFor(modelItem => item.CommentDate)</a>
										</div>
										<p>@Html.DisplayFor(modelItem => item.CommentContent)</p>
										
									</div>

                               </li>
                                 
                          }


							</ol>

                            <div id="respond">

                          @{ Html.RenderAction("Create", "Comment", new { PostID = Model.PostID }); }  

            

                           </div>
                
                       


						</section>
						
					</div>
					
					<!-- /Comments -->








<div class="cl"></div>



</div>    <!--  ZA DA SE ZATVORI RenderBody()    -->




<!-- Side Bar -->
					
                    <aside class="col-4">
						
						<div class="widget widget-style-1">
							<h4>Categories</h4>
							<ul>
                           
                                
                                <li><a href="../Categories?catname=Web Design">Web Design</a></li>
                                <li><a href="../Categories?catname=Graphic Design">Graphic Design</a></li>  
                                <li><a href="../Categories?catname=Motion Graphics">Motion Graphics</a></li> 
                                <li><a href="../Categories?catname=Usability"></a>Usability</li>
                                <li><a href="../Categories?catname=Mobile apps"></a>Mobile apps</li>                                   
                                
                            
							</ul>
						</div>
					
						<div class="widget widget-style-2">
							<h4>Archives</h4>
							<ul>
								<li><a href="#">October 2011</a></li>
								<li><a href="#">September 2011</a></li>
								<li><a href="#">August 2011</a></li>
								<li><a href="#">July 2011</a></li>
								<li><a href="#">June 2011</a></li>
							</ul>
						</div>
						
						
						
					</aside>

                   

				<!-- / Side Bar -->

MvcMyBlog/Views/Home/Edit.cshtml
@model MvcMyBlog.Models.Post

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Post</legend>

        @Html.HiddenFor(model => model.PostID)

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Text)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Text)
            @Html.ValidationMessageFor(model => model.Text)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CategoryPostID, "CategoryPost")
        </div>
        <div class="editor-field">
            @Html.DropDownList("CategoryPostID", String.Empty)
            @Html.ValidationMessageFor(model => model.CategoryPostID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Date)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Date)
            @Html.ValidationMessageFor(model => model.Date)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Tags)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Tags)
            @Html.ValidationMessageFor(model => model.Tags)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserName)
            @Html.ValidationMessageFor(model => model.UserName)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>